### ISSUE TITLE
Most ignored issue

### ISSUE THREAD

**Issue by none5969** [gautamajay52/TorrentLeech-Gdrive#48]
I request you to remove deploy to heroku button as peopl have started to abuse your repo 
This means that if heroku bans free dynos half of telegram will be down 

Please add heroku.yml so that people have to figure out how to deploy rather than creating unlimited bots and abusing them

**Comment by Gwenstephanie** [comment]
Hmm he has a valid point.

**Comment by none5969** [comment]
Due to this much abuse heroku will ban gautams repo and all his hardwork will go useless ..

**Comment by gautamajay52** [comment]
Not everyone can afford a VPS so here we come again to Heroku, I know one-day Heroku will ban this repo due to excessive use as it has done with other torrent leeching repo.

And everything has a way to solve, even people are deploying other torrents leeching repo despite those removed supporting the Heroku. **Not supporting is just slowing them down, not stopping.**

In the fork list of 100+ members in this repo, I don't think even 5% percent of people are using VPS to host this repo or **even thinking about that.**

And as per my knowledge, noob doesn't exploit anything. **People who are more willing to leech and hoard torrents exploit those free services and care more about not  getting banned**

**So, let's pray !!!**

**Comment by none5969** [comment]
Thanks for the LoL appreciate it bro ❤️❤️❤️😎😎🤔🥺🥺🥺😘

**Comment by none5969** [comment]
I am not lol you are lol heroku is banning lol 😂😂😂

**Comment by gautamajay52** [comment]
Why are you so happy?
